/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithSidebarImport } from './routes/_withSidebar'
import { Route as WithSidebarIndexImport } from './routes/_withSidebar/index'
import { Route as WithSidebarLabelsImport } from './routes/_withSidebar/labels'
import { Route as WithoutSidebarAuthTypeImport } from './routes/_withoutSidebar/auth.$type'

// Create/Update Routes

const WithSidebarRoute = WithSidebarImport.update({
  id: '/_withSidebar',
  getParentRoute: () => rootRoute,
} as any)

const WithSidebarIndexRoute = WithSidebarIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithSidebarRoute,
} as any)

const WithSidebarLabelsRoute = WithSidebarLabelsImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => WithSidebarRoute,
} as any)

const WithoutSidebarAuthTypeRoute = WithoutSidebarAuthTypeImport.update({
  id: '/_withoutSidebar/auth/$type',
  path: '/auth/$type',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withSidebar': {
      id: '/_withSidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithSidebarImport
      parentRoute: typeof rootRoute
    }
    '/_withSidebar/labels': {
      id: '/_withSidebar/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof WithSidebarLabelsImport
      parentRoute: typeof WithSidebarImport
    }
    '/_withSidebar/': {
      id: '/_withSidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithSidebarIndexImport
      parentRoute: typeof WithSidebarImport
    }
    '/_withoutSidebar/auth/$type': {
      id: '/_withoutSidebar/auth/$type'
      path: '/auth/$type'
      fullPath: '/auth/$type'
      preLoaderRoute: typeof WithoutSidebarAuthTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface WithSidebarRouteChildren {
  WithSidebarLabelsRoute: typeof WithSidebarLabelsRoute
  WithSidebarIndexRoute: typeof WithSidebarIndexRoute
}

const WithSidebarRouteChildren: WithSidebarRouteChildren = {
  WithSidebarLabelsRoute: WithSidebarLabelsRoute,
  WithSidebarIndexRoute: WithSidebarIndexRoute,
}

const WithSidebarRouteWithChildren = WithSidebarRoute._addFileChildren(
  WithSidebarRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof WithSidebarRouteWithChildren
  '/labels': typeof WithSidebarLabelsRoute
  '/': typeof WithSidebarIndexRoute
  '/auth/$type': typeof WithoutSidebarAuthTypeRoute
}

export interface FileRoutesByTo {
  '/labels': typeof WithSidebarLabelsRoute
  '/': typeof WithSidebarIndexRoute
  '/auth/$type': typeof WithoutSidebarAuthTypeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_withSidebar': typeof WithSidebarRouteWithChildren
  '/_withSidebar/labels': typeof WithSidebarLabelsRoute
  '/_withSidebar/': typeof WithSidebarIndexRoute
  '/_withoutSidebar/auth/$type': typeof WithoutSidebarAuthTypeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/labels' | '/' | '/auth/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/labels' | '/' | '/auth/$type'
  id:
    | '__root__'
    | '/_withSidebar'
    | '/_withSidebar/labels'
    | '/_withSidebar/'
    | '/_withoutSidebar/auth/$type'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WithSidebarRoute: typeof WithSidebarRouteWithChildren
  WithoutSidebarAuthTypeRoute: typeof WithoutSidebarAuthTypeRoute
}

const rootRouteChildren: RootRouteChildren = {
  WithSidebarRoute: WithSidebarRouteWithChildren,
  WithoutSidebarAuthTypeRoute: WithoutSidebarAuthTypeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_withSidebar",
        "/_withoutSidebar/auth/$type"
      ]
    },
    "/_withSidebar": {
      "filePath": "_withSidebar.tsx",
      "children": [
        "/_withSidebar/labels",
        "/_withSidebar/"
      ]
    },
    "/_withSidebar/labels": {
      "filePath": "_withSidebar/labels.tsx",
      "parent": "/_withSidebar"
    },
    "/_withSidebar/": {
      "filePath": "_withSidebar/index.tsx",
      "parent": "/_withSidebar"
    },
    "/_withoutSidebar/auth/$type": {
      "filePath": "_withoutSidebar/auth.$type.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
